require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HomeworkAnswerFilesController do

  # This should return the minimal set of attributes required to create a valid
  # HomeworkAnswerFile. As you add validations to HomeworkAnswerFile, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HomeworkAnswerFilesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all homework_answer_files as @homework_answer_files" do
      homework_answer_file = HomeworkAnswerFile.create! valid_attributes
      get :index, {}, valid_session
      assigns(:homework_answer_files).should eq([homework_answer_file])
    end
  end

  describe "GET show" do
    it "assigns the requested homework_answer_file as @homework_answer_file" do
      homework_answer_file = HomeworkAnswerFile.create! valid_attributes
      get :show, {:id => homework_answer_file.to_param}, valid_session
      assigns(:homework_answer_file).should eq(homework_answer_file)
    end
  end

  describe "GET new" do
    it "assigns a new homework_answer_file as @homework_answer_file" do
      get :new, {}, valid_session
      assigns(:homework_answer_file).should be_a_new(HomeworkAnswerFile)
    end
  end

  describe "GET edit" do
    it "assigns the requested homework_answer_file as @homework_answer_file" do
      homework_answer_file = HomeworkAnswerFile.create! valid_attributes
      get :edit, {:id => homework_answer_file.to_param}, valid_session
      assigns(:homework_answer_file).should eq(homework_answer_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HomeworkAnswerFile" do
        expect {
          post :create, {:homework_answer_file => valid_attributes}, valid_session
        }.to change(HomeworkAnswerFile, :count).by(1)
      end

      it "assigns a newly created homework_answer_file as @homework_answer_file" do
        post :create, {:homework_answer_file => valid_attributes}, valid_session
        assigns(:homework_answer_file).should be_a(HomeworkAnswerFile)
        assigns(:homework_answer_file).should be_persisted
      end

      it "redirects to the created homework_answer_file" do
        post :create, {:homework_answer_file => valid_attributes}, valid_session
        response.should redirect_to(HomeworkAnswerFile.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved homework_answer_file as @homework_answer_file" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomeworkAnswerFile.any_instance.stub(:save).and_return(false)
        post :create, {:homework_answer_file => {}}, valid_session
        assigns(:homework_answer_file).should be_a_new(HomeworkAnswerFile)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HomeworkAnswerFile.any_instance.stub(:save).and_return(false)
        post :create, {:homework_answer_file => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested homework_answer_file" do
        homework_answer_file = HomeworkAnswerFile.create! valid_attributes
        # Assuming there are no other homework_answer_files in the database, this
        # specifies that the HomeworkAnswerFile created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HomeworkAnswerFile.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => homework_answer_file.to_param, :homework_answer_file => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested homework_answer_file as @homework_answer_file" do
        homework_answer_file = HomeworkAnswerFile.create! valid_attributes
        put :update, {:id => homework_answer_file.to_param, :homework_answer_file => valid_attributes}, valid_session
        assigns(:homework_answer_file).should eq(homework_answer_file)
      end

      it "redirects to the homework_answer_file" do
        homework_answer_file = HomeworkAnswerFile.create! valid_attributes
        put :update, {:id => homework_answer_file.to_param, :homework_answer_file => valid_attributes}, valid_session
        response.should redirect_to(homework_answer_file)
      end
    end

    describe "with invalid params" do
      it "assigns the homework_answer_file as @homework_answer_file" do
        homework_answer_file = HomeworkAnswerFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomeworkAnswerFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => homework_answer_file.to_param, :homework_answer_file => {}}, valid_session
        assigns(:homework_answer_file).should eq(homework_answer_file)
      end

      it "re-renders the 'edit' template" do
        homework_answer_file = HomeworkAnswerFile.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HomeworkAnswerFile.any_instance.stub(:save).and_return(false)
        put :update, {:id => homework_answer_file.to_param, :homework_answer_file => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested homework_answer_file" do
      homework_answer_file = HomeworkAnswerFile.create! valid_attributes
      expect {
        delete :destroy, {:id => homework_answer_file.to_param}, valid_session
      }.to change(HomeworkAnswerFile, :count).by(-1)
    end

    it "redirects to the homework_answer_files list" do
      homework_answer_file = HomeworkAnswerFile.create! valid_attributes
      delete :destroy, {:id => homework_answer_file.to_param}, valid_session
      response.should redirect_to(homework_answer_files_url)
    end
  end

end
