require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionHomeworksController do

  # This should return the minimal set of attributes required to create a valid
  # QuestionHomework. As you add validations to QuestionHomework, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestionHomeworksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all question_homeworks as @question_homeworks" do
      question_homework = QuestionHomework.create! valid_attributes
      get :index, {}, valid_session
      assigns(:question_homeworks).should eq([question_homework])
    end
  end

  describe "GET show" do
    it "assigns the requested question_homework as @question_homework" do
      question_homework = QuestionHomework.create! valid_attributes
      get :show, {:id => question_homework.to_param}, valid_session
      assigns(:question_homework).should eq(question_homework)
    end
  end

  describe "GET new" do
    it "assigns a new question_homework as @question_homework" do
      get :new, {}, valid_session
      assigns(:question_homework).should be_a_new(QuestionHomework)
    end
  end

  describe "GET edit" do
    it "assigns the requested question_homework as @question_homework" do
      question_homework = QuestionHomework.create! valid_attributes
      get :edit, {:id => question_homework.to_param}, valid_session
      assigns(:question_homework).should eq(question_homework)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionHomework" do
        expect {
          post :create, {:question_homework => valid_attributes}, valid_session
        }.to change(QuestionHomework, :count).by(1)
      end

      it "assigns a newly created question_homework as @question_homework" do
        post :create, {:question_homework => valid_attributes}, valid_session
        assigns(:question_homework).should be_a(QuestionHomework)
        assigns(:question_homework).should be_persisted
      end

      it "redirects to the created question_homework" do
        post :create, {:question_homework => valid_attributes}, valid_session
        response.should redirect_to(QuestionHomework.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question_homework as @question_homework" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionHomework.any_instance.stub(:save).and_return(false)
        post :create, {:question_homework => {}}, valid_session
        assigns(:question_homework).should be_a_new(QuestionHomework)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionHomework.any_instance.stub(:save).and_return(false)
        post :create, {:question_homework => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question_homework" do
        question_homework = QuestionHomework.create! valid_attributes
        # Assuming there are no other question_homeworks in the database, this
        # specifies that the QuestionHomework created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionHomework.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => question_homework.to_param, :question_homework => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested question_homework as @question_homework" do
        question_homework = QuestionHomework.create! valid_attributes
        put :update, {:id => question_homework.to_param, :question_homework => valid_attributes}, valid_session
        assigns(:question_homework).should eq(question_homework)
      end

      it "redirects to the question_homework" do
        question_homework = QuestionHomework.create! valid_attributes
        put :update, {:id => question_homework.to_param, :question_homework => valid_attributes}, valid_session
        response.should redirect_to(question_homework)
      end
    end

    describe "with invalid params" do
      it "assigns the question_homework as @question_homework" do
        question_homework = QuestionHomework.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionHomework.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_homework.to_param, :question_homework => {}}, valid_session
        assigns(:question_homework).should eq(question_homework)
      end

      it "re-renders the 'edit' template" do
        question_homework = QuestionHomework.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionHomework.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_homework.to_param, :question_homework => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question_homework" do
      question_homework = QuestionHomework.create! valid_attributes
      expect {
        delete :destroy, {:id => question_homework.to_param}, valid_session
      }.to change(QuestionHomework, :count).by(-1)
    end

    it "redirects to the question_homeworks list" do
      question_homework = QuestionHomework.create! valid_attributes
      delete :destroy, {:id => question_homework.to_param}, valid_session
      response.should redirect_to(question_homeworks_url)
    end
  end

end
